# vim:fileencoding=utf-8:foldmethod=marker

include mocha.conf
include keybinds.conf

#: Fonts 

font_family             family="FiraMono Nerd Font Mono"
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               12.0

#: Theme colour overrides
active_border_color     #e0e4e5
inactive_border_color   #9ea3a7

#: Text cursor customization

cursor_shape            beam
cursor_shape_unfocused  hollow
cursor_trail            100

#: Scrollback

scrollbar               always
scrollbar_interactive   no
scrollbar_gap           0.2

#: Mouse

mouse_hide_wait         -1.0
url_style               straight
show_hyperlink_targets  yes
paste_actions           quote-urls-at-prompt,confirm,confirm-if-large
strip_trailing_spaces   smart

#: Terminal bell

enable_audio_bell       no
visual_bell_duration    2.0
bell_on_tab             "🔔 "

#: Window layout

confirm_os_window_close 0 
window_padding_width 10
window_margin_width 5
enabled_layouts Tall, *

#: Tab bar

tab_bar_edge            top
tab_bar_margin_width    10.0
tab_bar_margin_height   4.0 0.0
tab_bar_style           powerline
tab_bar_min_tabs        1
tab_powerline_style     round
active_tab_font_style   bold
inactive_tab_font_style normal

#: Color scheme

background_opacity      0.5

#: Advanced

notify_on_cmd_finish    unfocused 15.0

