$font = JetBrains Nerd Font
$background_img = /home/osaal/dotfiles/wallpapers/bg_1.jpg

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $background_img
    blur_passes = 3
}

input-field {
    monitor = 
    size = 20%, 5%
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1

    inner_color = rgb(11111b)
    outer_color = rgb(a6adc8)
    font_color = rgb(a6adc8)
    check_color =  rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)

    fade_on_empty = false
    rounding = -1

    font_family = $font
    placeholder_text = <i>Input password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 100

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME 
    color = $text
    font_size = 90
    font_family = $font
    position = 0, -200
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    color = $text
    font_size = 30
    font_family = $font
    position = 0, -380
    halign = center
    valign = top
}
